version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: fsc-refactoring-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  .postgres-data:
